### ISSUE TITLE
Exception: unknown tag: Caption

### ISSUE THREAD

**Issue by vinipsmaker** [chdemko/pandoc-latex-admonition#8]
```
$ pandoc -f docbook abc.xml --filter pandoc_latex_admonition.py -o abc.pdf
Traceback (most recent call last):
  File "pandoc_latex_admonition.py", line 790, in <module>
    main()
  File "pandoc_latex_admonition.py", line 786, in main
    return run_filter(admonition, prepare=prepare, finalize=finalize, doc=doc)
  File "/home/vinipsmaker/.local/lib/python3.8/site-packages/panflute/io.py", line 266, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/vinipsmaker/.local/lib/python3.8/site-packages/panflute/io.py", line 239, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/vinipsmaker/.local/lib/python3.8/site-packages/panflute/io.py", line 59, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/vinipsmaker/.local/lib/python3.8/site-packages/panflute/elements.py", line 1532, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter pandoc_latex_admonition.py:
Filter returned error status 1
zsh: exit 83    pandoc -f docbook abc.xml --filter pandoc_latex_admonition.py -o abc.pdf
```

**Comment by chdemko** [comment]
Fixed in last release
